# Generated by Django 5.1.3 on 2024-11-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0003_actor_actor_name_en_actor_actor_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_bio_ru',
            field=models.TextField(null=True),
        ),
    ]
